<section id="auth-section" class="py-20 bg-[#1C1C1C] text-white">
        <div class="container mx-auto px-4">    
            <div class="flex flex-col lg:flex-row gap-12 items-start">  
                <!-- Left Column: CTA & Auth Buttons -->
                <div class="lg:w-1/2 text-left">
                    <h2 class="text-3xl font-bold mb-2">Ready to get on the road?</h2>
                    <p class="text-[#848484] mb-8 text-lg font-bold pb-3">
                        Join thousands of Sri Lankan drivers who have switched to the digital platform. 
                        Register today or log in to manage your profile.
                    </p>
                        @auth
                            <div class="py-3 inline-block">
                                <p class="mb-4 text-gray-300">Logged in as <span class="text-white font-bold">{{ Auth::user()->name }}</span></p>
                                <x-bladewind.button 
                                    tag="a" 
                                    {{-- href="{{ route('dashboard.index') }}" --}}
                                    size="regular"
                                    color="blue">
                                    Go to Dashboard
                                </x-bladewind.button>
                            </div>
                        @else
                            <div class="flex flex-col sm:flex-row gap-4">
                                <x-bladewind.button 
                                    tag="a" 
                                    href="{{ route('login.index') }}"
                                    size="small"
                                    color="blue">
                                    Login
                                </x-bladewind.button>

                                <x-bladewind.button 
                                    tag="a" 
                                    {{-- href="{{ route('register') }}" --}}
                                    size="small"
                                    outline="true"
                                    color="white">
                                    Register New Account
                                </x-bladewind.button>
                            </div>
                        @endauth
                </div>

                <!-- Right Column: FAQ Accordion -->
                <div class="bg-transparent rounded-lg p-1 overflow-hidden text-gray-800">
                <x-bladewind.accordion color="gray">
                    <x-bladewind.accordion.item title="Is the digital license valid for police checks?" open="true">
                        Yes, the digital license generated by this system is fully recognized by the Sri Lanka Police and Department of Motor Traffic.
                    </x-bladewind.accordion.item>
                    
                    <x-bladewind.accordion.item title="How long does the verification take?">
                        For new accounts, NIC verification is instant. License conversion requests are typically processed within 24 hours.
                    </x-bladewind.accordion.item>
                    <x-bladewind.accordion.item title="Can I pay my fines online?">
                        Yes, you can pay spot fines and administrative penalties using any major credit/debit card through the secure payment gateway.
                    </x-bladewind.accordion.item>
                </x-bladewind.accordion>
            </div>
            </div>

        </div>
</section>