<x-bladewind::modal
    icon_css="bg-gray-500 text-white p-2.5 rounded-full"
    title="Terms and Conditions"
    blur_size="medium"
    name="terms">
            <div class="p-6 flex flex-col space-y-4 bg-gradient-to-b from-white/60 to-white/40 dark:from-gray-900/60 dark:to-gray-900/40 rounded-lg">
                <div class="prose prose-lg dark:prose-invert overflow-y-auto custom-scrollbar max-h-[60vh] sm:max-h-[70vh] px-2">
                    <div class="flex items-start gap-3 mb-4">
                        <svg class="w-10 h-10 text-indigo-600" viewBox="0 0 24 24" fill="none" aria-hidden="true">
                            <path d="M12 2L3 7v6c0 5 4 9 9 9s9-4 9-9V7l-9-5z" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
                            <path d="M9 12l2 2 4-4" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
                        </svg>
                        <div>
                            <h1 class="text-2xl font-extrabold text-indigo-700">Terms and Conditions of Use</h1>
                            <p class="text-sm text-indigo-600 mt-1">Digital License Portal — please read carefully</p>
                        </div>
                    </div>

                    <div class="warning-box bg-yellow-50 border-l-4 border-yellow-400 text-yellow-800 p-4 rounded-md flex gap-3 items-start">
                        <svg class="w-5 h-5 mt-0.5 text-yellow-600" viewBox="0 0 24 24" fill="none" aria-hidden="true">
                            <path d="M12 9v4" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
                            <path d="M12 17h.01" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
                            <path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z" stroke="currentColor" stroke-width="1" stroke-linecap="round" stroke-linejoin="round"/>
                        </svg>
                        <div class="text-sm">
                            <b>WARNING:</b> Please read these terms carefully. Falsifying information during a government application is a strictly punishable offense under the <i>Digital Crimes Act of 2024</i>.
                        </div>
                    </div>

                    <p class="text-sm text-gray-600 dark:text-gray-300">
                        Effective Date:
                        <span class="inline-block bg-indigo-100 text-indigo-800 text-xs px-2 py-0.5 rounded-full ml-2">October 25, 2025</span>
                    </p>

                    <h2 class="text-xl font-semibold text-sky-600 mt-4">1. Acceptance of Terms</h2>
                    <p class="text-gray-700 dark:text-gray-200">
                        By accessing and using the Digital License Portal (hereinafter referred to as "the Service"), you agree to comply with and be bound by these Terms and Conditions ("Terms"). If you do not agree to these Terms, you must not proceed with the digital license application.
                    </p>

                    <h2 class="text-xl font-semibold text-sky-600 mt-4">2. Eligibility and Verification</h2>
                    <p class="text-gray-700 dark:text-gray-200">To be eligible for a digital license, you must meet the following criteria:</p>
                    <ul class="list-disc pl-5 mt-2 text-gray-700 dark:text-gray-200 space-y-1">
                        <li class="marker:text-indigo-500">You must be a legal resident of the issuing jurisdiction.</li>
                        <li class="marker:text-indigo-500">You must possess a valid, government-issued national identification number.</li>
                        <li class="marker:text-indigo-500">You must hold a valid, non-expired physical driving license or learner's permit.</li>
                    </ul>
                    <p class="text-gray-700 dark:text-gray-200 mt-2">
                        You explicitly consent to the automated verification of your <b>biometric data</b> (specifically facial geometry and fingerprints) against the National Transport Database.
                    </p>

                    <h2 class="text-xl font-semibold text-sky-600 mt-4">3. Digital Representation &amp; Validity</h2>
                    <p class="text-gray-700 dark:text-gray-200">
                        The Digital License generated by this portal is a legal equivalent to the physical card for identification and traffic enforcement purposes. However, please note:
                    </p>
                    <ul class="list-disc pl-5 mt-2 text-gray-700 dark:text-gray-200 space-y-1">
                        <li class="marker:text-indigo-500">You are responsible for ensuring your mobile device is charged and functional.</li>
                        <li class="marker:text-indigo-500">Screenshots, photos, or printed copies of the QR code are <b>NOT</b> valid forms of identification.</li>
                        <li class="marker:text-indigo-500">Law enforcement officers may request to scan the live QR code generated by the official app.</li>
                    </ul>

                    <h2 class="text-xl font-semibold text-sky-600 mt-4">4. Privacy and Data Security</h2>
                    <p class="text-gray-700 dark:text-gray-200">
                        We value your privacy. Your personal data is encrypted using <i>AES-256 standard</i> and stored in compliance with the Data Protection Act. We do not share your biometric data with third-party commercial entities under any circumstances.
                    </p>

                    <h2 class="text-xl font-semibold text-sky-600 mt-4">5. Revocation and Suspension</h2>
                    <p class="text-gray-700 dark:text-gray-200">
                        The issuing authority reserves the right to remotely revoke or suspend your digital license certificate if:
                    </p>
                    <ul class="list-disc pl-5 mt-2 text-gray-700 dark:text-gray-200 space-y-1">
                        <li class="marker:text-indigo-500">Your physical license is suspended by a court of law.</li>
                        <li class="marker:text-indigo-500">Fraudulent activity is detected on your account.</li>
                        <li class="marker:text-indigo-500">You fail to renew your medical fitness certificate.</li>
                    </ul>

                    <p class="italic text-gray-600 dark:text-gray-400 mt-4">
                        By clicking "Accept", you acknowledge that you have read and understood these terms.
                    </p>
                </div>
            </div>

</x-bladewind::modal>